$mainMod = SUPER
$terminal = kitty
$fileManager = dolphin
$menu = rofi


# Sources

source = ~/.config/hypr/mouse.conf

# workspaces

# Scroll through existing workspaces
bind = $mainMod, mouse_down, workspace, e+1
bind = $mainMod, mouse_up, workspace, e-1

# # Cycle through workspaces with keyboard keys
bind = $mainMod, right, workspace, +1
bind = $mainMod, left, workspace, -1

# Move windows between workspaces
bind = $mainMod CTRL SHIFT, right, movetoworkspace, +1
bind = $mainMod CTRL SHIFT, left, movetoworkspace, -1

# Move and resize windows with Super + Mouse clicks
bindm = SUPER, mouse:272, movewindow
bindm = SUPER, mouse:273, resizewindow

# screenshots
bind = , PRINT, exec, hyprshot -m region --clipboard-only
bind = SHIFT, PRINT, exec, hyprshot -m window --clipboard-only
# main
bindr= $mainMod, Super_L, exec, rofi -show drun

# Volume Control with Dunst Square Popups
bindel = , XF86AudioRaiseVolume, exec, wpctl set-volume @DEFAULT_AUDIO_SINK@ 5%+ && dunstify -a "changeVolume" -u low -i audio-volume-high -h string:x-dunst-stack-tag:volume -h int:value:"$(wpctl get-volume @DEFAULT_AUDIO_SINK@ | awk '{print $2 * 100}')" "Volume"
bindel = , XF86AudioLowerVolume, exec, wpctl set-volume @DEFAULT_AUDIO_SINK@ 5%- && dunstify -a "changeVolume" -u low -i audio-volume-low -h string:x-dunst-stack-tag:volume -h int:value:"$(wpctl get-volume @DEFAULT_AUDIO_SINK@ | awk '{print $2 * 100}')" "Volume"
bindl  = , XF86AudioMute,        exec, wpctl set-mute @DEFAULT_AUDIO_SINK@ toggle && dunstify -a "changeVolume" -u low -i audio-volume-muted -h string:x-dunst-stack-tag:volume "Muted"

# Increase/Decrease Laptop Brightness
bindel = , XF86MonBrightnessUp, exec, brightnessctl set +5%
bindel = , XF86MonBrightnessDown, exec, brightnessctl set 5%-

# other
bind = SUPER, G, togglegroup
bind = SUPER, s, exec, kitty ytm
bind = $mainMod, Q, exec, $terminal
bind = $mainMod, C, killactive,
bind = $mainMod, M, exec, command -v hyprshutdown >/dev/null 2>&1 && hyprshutdown || hyprctl dispatch exit
bind = $mainMod, E, exec, $fileManager
bind = $mainMod, V, togglefloating,
bind = $mainMod, R, exec, $menu
# window rules
animations {
    enabled = true
    bezier = myBezier, 0.17, 0.67, 0.1, 1.15
    animation = windows, 1, 6, myBezier
    animation = windowsOut, 1, 6, myBezier, popin 80%
    animation = border, 1, 10, default
    animation = borderangle, 1, 8, default
    animation = fade, 1, 7, default
    animation = workspaces, 1, 5, myBezier, slide
}
decoration {
    rounding = 12
}

# execs
exec-once = hyprpaper
exec-once = waybar
exec-once = hyprsunset -t 5000 -- warm colors
