# ~/.config/hypr/mouse.conf

# Define theme names (CRITICAL)
env = HYPRCURSOR_THEME,catppuccin-frappe-pink-cursors
env = XCURSOR_THEME,catppuccin-frappe-pink-cursors

# Define theme sizes (Using 25 to bypass sizing bugs)
env = HYPRCURSOR_SIZE,25
env = XCURSOR_SIZE,25

# Force the theme on startup (ONLY ONE LINE - Bibata removed)
exec-once = hyprctl setcursor catppuccin-frappe-pink-cursors 25

# Mouse physics and speed
input {
    accel_profile = flat
    force_no_accel = true
    touchpad {
        disable_while_typing = true
        # Add this line to turn the trackpad off entirely:
        clickfinger_behavior = false
    }
}
